-- Phase C — Cue Mirror, Component Two (Format Drafter).
-- format_drafts: a structured, source-traceable report draft generated by
-- mapping a client's canonical clinical data into the SLP's locked template.
-- Every clinical claim in draft_sections carries its source; every lexicon
-- swap is recorded so the Cue draft view can show §language-discipline
-- visibility. RLS scopes every row to the authoring clinician.

create table if not exists public.format_drafts (
  id                 uuid primary key default gen_random_uuid(),
  user_id            uuid not null references auth.users(id) on delete cascade,
  client_id          uuid not null references public.clients(id) on delete cascade,
  template_id        uuid not null references public.format_templates(id) on delete cascade,
  date_range_start   date,
  date_range_end     date,
  date_range_preset  text check (date_range_preset in ('weekly','monthly','quarterly','all_sessions','custom')),
  -- [{section_name, content, source_claims:[{claim_text, source_type, source_id, source_excerpt}], lexicon_swaps:[{original, replacement, position_in_content}]}, ...]
  draft_sections     jsonb not null default '[]'::jsonb,
  -- { model, tokens, latency_ms, template_version_snapshot }
  generation_metadata jsonb default '{}'::jsonb,
  status             text not null default 'draft' check (status in ('draft','reviewed','signed','archived')),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  generated_at       timestamptz not null default now(),
  is_fixture         boolean default false,
  notes              text
);

alter table public.format_drafts enable row level security;

create policy "format_drafts_select_own"
  on public.format_drafts for select
  using (auth.uid() = user_id);

create policy "format_drafts_insert_own"
  on public.format_drafts for insert
  with check (auth.uid() = user_id);

create policy "format_drafts_update_own"
  on public.format_drafts for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "format_drafts_delete_own"
  on public.format_drafts for delete
  using (auth.uid() = user_id);

create index if not exists format_drafts_user_client_template_idx
  on public.format_drafts (user_id, client_id, template_id, generated_at desc);
